/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRINGS_H_RPCGEN
#define _STRINGS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct stuff {
	char *name;
	int val;
};
typedef struct stuff stuff;

#define TEST_PROG 0x33388888
#define TEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TEST_FUNC 1
extern  char ** test_func_1(stuff *, CLIENT *);
extern  char ** test_func_1_svc(stuff *, struct svc_req *);
extern int test_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TEST_FUNC 1
extern  char ** test_func_1();
extern  char ** test_func_1_svc();
extern int test_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_stuff (XDR *, stuff*);

#else /* K&R C */
extern bool_t xdr_stuff ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRINGS_H_RPCGEN */
