/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "strings.h"

bool_t
xdr_stuff (XDR *xdrs, stuff *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 64))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->val))
		 return FALSE;
	return TRUE;
}
